apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexric-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "xapp-kpm-moni.fullname" . }}-nfs-pvc
  labels:
    {{- include "xapp-kpm-moni.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "xapp-kpm-moni.fullname" . }}-nfs-pv
  labels:
    {{- include "xapp-kpm-moni.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "xapp-kpm-moni.fullname" . }}-nfs-pvc
  labels:
    {{- include "xapp-kpm-moni.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
