{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "xapp-rc-moni.fullname" . }}
  labels:
    {{- include "xapp-rc-moni.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "xapp-rc-moni.fullname" . }}
  labels:
    {{- include "xapp-rc-moni.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "xapp-rc-moni.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "xapp-rc-moni.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
