apiVersion: v2
name: f1-split2
type: application
icon: http://www.openairinterface.org/wp-content/uploads/2015/06/cropped-oai_final_logo.png
version: 2.1.0
description: Charts for testing f1-split2 ran use case with two du/ru

appVersion: 2.1.0

keywords:
  - 5GCN
  - AMF
  - SMF
  - NRF
  - UPF
  - UDM
  - UDR
  - AUSF
  - CU
  - DU
  - NRUE
  - Traffic_server
  - FLEXRIC

maintainers:
  - name:  OPENAIRINTERFACE
    email: contact@openairinterface.org

dependencies:
- condition: mysql.enabled
  name: mysql
  repository: "file://../../oai-5g-core/mysql"
  version: 9.0.1
- condition: oai-nrf.enabled
  name: oai-nrf
  repository: "file://../../oai-5g-core/oai-nrf"
  version: v2.1.0
- condition: oai-udr.enabled
  name: oai-udr
  repository: "file://../../oai-5g-core/oai-udr"
  version: v2.1.0
- condition: oai-udm.enabled
  name: oai-udm
  repository: "file://../../oai-5g-core/oai-udm"
  version: v2.1.0
- condition: oai-ausf.enabled
  name: oai-ausf
  repository: "file://../../oai-5g-core/oai-ausf"
  version: v2.1.0
- condition: oai-amf.enabled
  name: oai-amf
  repository: "file://../../oai-5g-core/oai-amf"
  version: v2.1.0
- condition: oai-smf.enabled
  name: oai-smf
  repository: "file://../../oai-5g-core/oai-smf"
  version: v2.1.0
- condition: oai-upf.enabled
  name: oai-upf
  repository: "file://../../oai-5g-core/oai-upf"
  version: v2.1.0
- condition: oai-cu.enabled
  name: oai-cu
  repository: "file://../../oai-5g-ran/oai-cu"
  version: 2.1.0
- condition: oai-du1.enabled
  name: oai-du1
  repository: "file://../../oai-5g-ran/oai-du1"
  version: 2.1.0
- condition: oai-du2.enabled
  name: oai-du2
  repository: "file://../../oai-5g-ran/oai-du2"
  version: 2.1.0
- condition: oai-nr-ue.enabled
  name: oai-nr-ue
  repository: "file://../../oai-5g-ran/oai-nr-ue"
  version: 2.1.0
- condition: oai-traffic-server.enabled
  name: oai-traffic-server
  repository: "file://../../oai-5g-core/oai-traffic-server"
  version: v1
- condition: oai-ric.enabled
  name: oai-ric
  repository: "file://../../oai-5g-ran/oai-5g-ric/"
  version: v0.1.0
- condition: xapp-kpm-moni.enabled
  name: xapp-kpm-moni
  repository: "file://../../oai-5g-ran/xapp-kpm-moni"
  version: v0.1.0